// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/koteyye/shortener/internal/app/models"
)

// MockShortener is a mock of Shortener interface.
type MockShortener struct {
	ctrl     *gomock.Controller
	recorder *MockShortenerMockRecorder
}

// MockShortenerMockRecorder is the mock recorder for MockShortener.
type MockShortenerMockRecorder struct {
	mock *MockShortener
}

// NewMockShortener creates a new mock instance.
func NewMockShortener(ctrl *gomock.Controller) *MockShortener {
	mock := &MockShortener{ctrl: ctrl}
	mock.recorder = &MockShortenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortener) EXPECT() *MockShortenerMockRecorder {
	return m.recorder
}

// AddShortURL mocks base method.
func (m *MockShortener) AddShortURL(ctx context.Context, url, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddShortURL", ctx, url, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddShortURL indicates an expected call of AddShortURL.
func (mr *MockShortenerMockRecorder) AddShortURL(ctx, url, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddShortURL", reflect.TypeOf((*MockShortener)(nil).AddShortURL), ctx, url, userID)
}

// Batch mocks base method.
func (m *MockShortener) Batch(ctx context.Context, originalList []*models.OriginURLList, userID string) ([]*models.URLList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Batch", ctx, originalList, userID)
	ret0, _ := ret[0].([]*models.URLList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Batch indicates an expected call of Batch.
func (mr *MockShortenerMockRecorder) Batch(ctx, originalList, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Batch", reflect.TypeOf((*MockShortener)(nil).Batch), ctx, originalList, userID)
}

// DeleteURLByUser mocks base method.
func (m *MockShortener) DeleteURLByUser(ctx context.Context, urls []string, userID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteURLByUser", ctx, urls, userID)
}

// DeleteURLByUser indicates an expected call of DeleteURLByUser.
func (mr *MockShortenerMockRecorder) DeleteURLByUser(ctx, urls, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteURLByUser", reflect.TypeOf((*MockShortener)(nil).DeleteURLByUser), ctx, urls, userID)
}

// GetDBPing mocks base method.
func (m *MockShortener) GetDBPing(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBPing", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetDBPing indicates an expected call of GetDBPing.
func (mr *MockShortenerMockRecorder) GetDBPing(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBPing", reflect.TypeOf((*MockShortener)(nil).GetDBPing), ctx)
}

// GetOriginURL mocks base method.
func (m *MockShortener) GetOriginURL(ctx context.Context, shortURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginURL", ctx, shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginURL indicates an expected call of GetOriginURL.
func (mr *MockShortenerMockRecorder) GetOriginURL(ctx, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginURL", reflect.TypeOf((*MockShortener)(nil).GetOriginURL), ctx, shortURL)
}

// GetShortURLFromOriginal mocks base method.
func (m *MockShortener) GetShortURLFromOriginal(ctx context.Context, originalURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortURLFromOriginal", ctx, originalURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortURLFromOriginal indicates an expected call of GetShortURLFromOriginal.
func (mr *MockShortenerMockRecorder) GetShortURLFromOriginal(ctx, originalURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortURLFromOriginal", reflect.TypeOf((*MockShortener)(nil).GetShortURLFromOriginal), ctx, originalURL)
}

// GetURLByUser mocks base method.
func (m *MockShortener) GetURLByUser(ctx context.Context, userID string) ([]*models.AllURLs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLByUser", ctx, userID)
	ret0, _ := ret[0].([]*models.AllURLs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLByUser indicates an expected call of GetURLByUser.
func (mr *MockShortenerMockRecorder) GetURLByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLByUser", reflect.TypeOf((*MockShortener)(nil).GetURLByUser), ctx, userID)
}
